# -*- coding: utf-8 -*-
"""gENE_CLASSIFICATIONipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18vZfN7R1H2J7MEjoAydppi52O5ekQuYo
"""

# =====================================================================
# DNA Sequence Classification into Functional Gene Families
# MSc Coursework / Deep Learning Pipeline
# =====================================================================

# 1. Data Handling & Visualization
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sns
import seaborn as sns
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras import layers
from sklearn.metrics import classification_report, accuracy_score, f1_score
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from Bio.Seq import Seq
from Bio.SeqUtils import gc_fraction

# Diagram tuning
sns.set_theme()

# 2. Data Loading & Exploratory Data Analysis (EDA)
# Sourced locally - ensures the project runs out-of-the-box
humandata = pd.read_table('human_data.txt')

print("Dataset Structure (First 5 rows):")
print(humandata.head())
print("\nDataset Info:")
print(humandata.info())

# Dynamic feature evaluation on Sample 1
print(f'\nLength of Sequence 1: {len(humandata["sequence"][0])}')
my_seq = Seq(humandata["sequence"][0])
print(f"Complement: {my_seq.complement()[:50]}...")
print(f"Reverse Complement: {my_seq.reverse_complement()[:50]}...")
print(f"GC Fraction: {gc_fraction(my_seq):.4f}")

# Calculate length distribution across the dataset
humandata["length"] = humandata.sequence.apply(lambda x: len(x))
plt.figure(figsize=(8, 5))
plt.hist(humandata["length"], bins=50, color='#34495e', alpha=0.8)
plt.title("Distribution of Length of DNA Sequences")
plt.xlabel("Sequence Length")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

# 3. Data Preprocessing & Feature Engineering (6-mers)
def getKmers(sequence, size=6):
    return [sequence[x:x+size].upper() for x in range(len(sequence) - size + 1)]

# Transforming sequences into NLP "sentences"
humandata['words'] = humandata.apply(lambda x: getKmers(x['sequence']), axis=1)
humandata["in_string"] = humandata["words"].apply(lambda x: ' '.join(x))
y = humandata.loc[:, 'class'].values

# Tokenization (Integer Encoding)
tokenizer = Tokenizer()
tokenizer.fit_on_texts(humandata["in_string"])
X_sequences = tokenizer.texts_to_sequences(humandata["in_string"])

# Sequence Padding
max_len = 500
X_pad = pad_sequences(X_sequences, maxlen=max_len, padding='post', truncating='post')
vocab_size = len(tokenizer.word_index) + 1

# Train/Test Validation Split (Stratified Logic)
X_train, X_test, y_train, y_test = train_test_split(X_pad, y, test_size=0.2, random_state=42)

print(f"\nVocabulary Size: {vocab_size}")
print(f"Training Tensor Shape: {X_train.shape}")

# 4. Deep Learning Architecture Design (Proposed CNN-BiLSTM)
model = tf.keras.Sequential([
    layers.Input(shape=(max_len,)),

    # Layer 1: Dense Continuous Embeddings
    layers.Embedding(input_dim=vocab_size, output_dim=64),

    # Layer 2: Conv1D - Identifies local motifs
    layers.Conv1D(64, kernel_size=5, activation='relu'),
    layers.MaxPooling1D(pool_size=4),

    # Layer 3: Bidirectional LSTM - Multi-directional syntax mapping
    layers.Bidirectional(layers.LSTM(32)),

    # Layer 4: Dense Layers & Stochastic Regularization
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(7, activation='softmax')
])

model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

model.summary()

# 5. Network Training Execution
history = model.fit(
    X_train, y_train,
    epochs=15,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

# 6. Evaluation Curves Visualization
plt.figure(figsize=(14, 5))

# Plot Accuracy Trends
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Training Accuracy', marker='o', color='#3498db')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy', marker='s', color='#2ecc71')
plt.title('Training vs Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)

# Plot Loss Trends
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Training Loss', marker='o', color='#e74c3c')
plt.plot(history.history['val_loss'], label='Validation Loss', marker='s', color='#f39c12')
plt.title('Training vs Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)

plt.tight_layout()
plt.show()

# 7. Comprehensive Model Evaluation
predictions = np.argmax(model.predict(X_test), axis=1)
print(f"\nFinal Test Set Accuracy Score: {accuracy_score(y_test, predictions):.5f}")
print("\nDetailed Performance Report Across the 7 Gene Families:\n")
print(classification_report(y_test, predictions))

# Generalization Gap Analysis
train_loss, train_accuracy = model.evaluate(X_train, y_train, verbose=0)
test_loss, test_accuracy = model.evaluate(X_test, y_test, verbose=0)

print("-" * 40)
print(f"{'Performance Metric':<22} | {'Value':<12}")
print("-" * 40)
print(f"{'Training Accuracy':<22} | {train_accuracy:.5f}")
print(f"{'Test Accuracy':<22} | {test_accuracy:.5f}")
print("-" * 40)
print(f"{'Generalization Gap':<22} | {abs(train_accuracy - test_accuracy):.5f}")
print("-" * 40)

# 8. Benchmarking Against Traditional Classifiers
print("\nExecuting Benchmarking Models (CountVectorizer Framework)...")
cv = CountVectorizer(ngram_range=(4,4))
X_cv = cv.fit_transform(humandata["in_string"])
y_cv = humandata['class'].values

X_train_cv, X_test_cv, y_train_cv, y_test_cv = train_test_split(X_cv, y_cv, test_size=0.2, random_state=42)

def print_metrics(y_true, y_pred, name):
    accuracy = accuracy_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred, average='macro') # Using macro average due to class imbalance
    print(f"--- {name} Benchmark ---")
    print(f"Accuracy: {accuracy:.5f}")
    print(f"Macro F1 Score: {f1:.5f}\n")

# Decision Tree Benchmark
dt = DecisionTreeClassifier()
dt.fit(X_train_cv, y_train_cv)
print_metrics(y_test_cv, dt.predict(X_test_cv), "Decision Tree")

# Random Forest Benchmark
rf = RandomForestClassifier(n_jobs=-1)
rf.fit(X_train_cv, y_train_cv)
print_metrics(y_test_cv, rf.predict(X_test_cv), "Random Forest")

# Naive Bayes Benchmark
nb = MultinomialNB(alpha=0.1)
nb.fit(X_train_cv, y_train_cv)
print_metrics(y_test_cv, nb.predict(X_test_cv), "Naive Bayes")

